language: c
dist: trusty

cache:
  directories:
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

matrix:
  include:
    - env: ARGS=""
      compiler: ": #stack 8.0.2"

    - env: ARGS="--resolver lts-11.22"
      compiler: ": #stack 8.2.2"

    - env: ARGS="--resolver lts-12.12"
      compiler: ": #stack 8.4.3"

    - env: ARGS="--resolver nightly"
      compiler: ": #stack nightly"

  allow_failures:
    - env: ARGS="--resolver nightly"
      compiler: ": #stack nightly"

before_install:
  - unset CC
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack $ARGS setup

script:
  - stack $ARGS --no-terminal test --flag "cacophony:build-tools" --bench --no-run-benchmarks --haddock --no-haddock-deps
  - stack $ARGS sdist
